[package]
name = "axum_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
axum = "0.8.4"
thiserror = "2.0.12"
tokio = { version =" 1.45.1", features = ["rt-multi-thread"] }
